[tool.poetry]
name = "nb-cli"
version = "0.1.0"
description = ""
authors = ["Behzad Samadi"]
readme = "README.md"
packages = [{include = "nb_cli"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
